apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fraud-api-monitor
  namespace: datalake
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: fraud-api
  endpoints:
  - port: http
    path: /metrics