apiVersion: batch/v1
kind: CronJob
metadata:
  name: spark-treino-diario
  namespace: datalake
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: spark
          securityContext:
            runAsUser: 1001
            runAsNonRoot: true
          containers:
          - name: spark
            image: acrmlopspix.azurecr.io/spark-custom:latest
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "1000m"
            command:
              - "/opt/bitnami/spark/bin/spark-submit"
              - "--master"
              - "local[*]"
              - "--deploy-mode"
              - "client"
              - "--name"
              - "pix-treino-diario"
              - "--conf"
              - "spark.driver.extraJavaOptions=-Duser.home=/tmp -Duser.name=spark -Djava.security.krb5.conf=/dev/null"
              - "/scripts/pix_fraud_pipeline.py"
            env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-service.datalake.svc.cluster.local:5000"
            - name: MLFLOW_S3_ENDPOINT
              value: "http://bucket-minio.datalake.svc.cluster.local:9000"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secret-key
            volumeMounts:
            - name: script-volume
              mountPath: /scripts
          volumes:
          - name: script-volume
            configMap:
              name: spark-treino-code
          restartPolicy: Never