apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: datalake
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-executor-role
  namespace: datalake
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets", "services"]
  verbs: ["get", "watch", "list"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: datalake
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-executor-role
subjects:
- kind: ServiceAccount
  name: spark
  namespace: datalake