apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-streaming-job
  namespace: datalake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-streaming
  template:
    metadata:
      labels:
        app: spark-streaming
    spec:
      serviceAccountName: spark
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
      containers:
      - name: spark
        image: acrmlopspix.azurecr.io/spark-custom:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: KAFKA_USER
          value: "spark-kafka-user"
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spark-kafka-user
              key: password
        - name: HADOOP_USER_NAME
          value: "spark"
        - name: USER
          value: "spark"
        - name: LOGNAME
          value: "spark"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
        - name: KAFKA_BOOTSTRAP
          value: "pix-cluster-kafka-bootstrap:9092"
        - name: REDIS_HOST
          value: "redis-service.datalake.svc.cluster.local"
        command:
          - "/opt/bitnami/spark/bin/spark-submit"
          - "--master"
          - "local[*]"
          - "--deploy-mode"
          - "client"
          - "--name"
          - "pix-streaming"
          - "--conf"
          - "spark.sql.shuffle.partitions=2"
          - "--conf"
          - "spark.default.parallelism=2"
          - "--conf"
          - "spark.driver.extraJavaOptions=-Duser.home=/tmp -Duser.name=spark -Djava.security.krb5.conf=/dev/null"
          - "/scripts/pix_streaming_pipeline.py"
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: spark-streaming-code