apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-streaming-job
  namespace: datalake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-streaming
  template:
    metadata:
      labels:
        app: spark-streaming
    spec:
      serviceAccountName: spark
      containers:
      - name: spark
        image: bitnami/spark:3.5.1
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
        - name: KAFKA_BOOTSTRAP
          value: "pix-cluster-kafka-bootstrap:9092"
        - name: REDIS_HOST
          value: "redis-service.datalake.svc.cluster.local"
        command:
          - "/opt/bitnami/spark/bin/spark-submit"
          - "--master"
          - "k8s://https://kubernetes.default.svc"
          - "--deploy-mode"
          - "cluster"
          - "--name"
          - "pix-streaming"
          - "--conf"
          - "spark.kubernetes.container.image=bitnami/spark:3.5.1"
          - "--conf"
          - "spark.kubernetes.namespace=datalake"
          - "--conf"
          - "spark.kubernetes.authenticate.driver.serviceAccountName=spark"
          - "--conf"
          - "spark.executor.instances=1"
          - "--conf"
          - "spark.executor.memory=1g"
          - "--conf"
          - "spark.executor.cores=1"
          - "--packages"
          - "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262"
          - "/scripts/pix_streaming_pipeline.py"
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: spark-streaming-code