apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-streaming-job
  namespace: datalake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-streaming
  template:
    metadata:
      labels:
        app: spark-streaming
    spec:
      containers:
      - name: spark
        image: spark:3.5.1
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        command:
          - "bash"
          - "-c"
          - >
            mkdir -p /tmp/pip_libs &&
            pip install --no-cache-dir --target /tmp/pip_libs boto3==1.33.13 numpy pandas &&
            export PYTHONPATH=$PYTHONPATH:/tmp/pip_libs &&
            /opt/spark/bin/spark-submit --conf spark.jars.ivy=/tmp/.ivy2 --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1 /scripts/pix_streaming_pipeline.py
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
      volumes:
      - name: script-volume
        configMap:
          name: spark-streaming-code